import 'bootstrap';
import './pengajuan';
import './history.js';
import './navbar.js';
import './cart.js';
import './detail.js';
import flatpickr from "flatpickr";
import "flatpickr/dist/flatpickr.min.css";
import './sidebar.js';
import './imageUploader.js';
import './item-table.js';
import './purchase_order.js';
import './category-table.js';
import './formPO.js';
import './showPO.js';
